# Generated by Django 4.0.5 on 2022-07-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reservation_statuses',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_information', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reservation_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.reservation_status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
