# Generated by Django 4.0.5 on 2022-07-05 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation_status',
            new_name='ReservationStatus',
        ),
    ]
