# Generated by Django 4.0.5 on 2022-07-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_reservation_status_reservationstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='resevations',
        ),
    ]
