# Generated by Django 4.0.5 on 2022-07-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
